name: 'Display Quote'
description: 'Display the Quote and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we displayed quote'
runs:
  using: 'node16'
  main: 'index.js'
